// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyClrywmSFeidRnu-vayyamHEGcHMevpEyM',
    appId: '1:719549052862:web:5dca71e2902a4139db2bef',
    messagingSenderId: '719549052862',
    projectId: 'yolda-destek',
    authDomain: 'yolda-destek.firebaseapp.com',
    storageBucket: 'yolda-destek.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARZrU5TtpygtTiuQK3BeQPdChgh4SEtjQ',
    appId: '1:719549052862:android:d9a0277c216ca922db2bef',
    messagingSenderId: '719549052862',
    projectId: 'yolda-destek',
    storageBucket: 'yolda-destek.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGcj63N7T6W3T5AA_L705p_NNX_PINAI8',
    appId: '1:719549052862:ios:47b93c2c3cd73312db2bef',
    messagingSenderId: '719549052862',
    projectId: 'yolda-destek',
    storageBucket: 'yolda-destek.appspot.com',
    iosBundleId: 'com.yoldadestek.yoldadestek',
  );
}
